# images can built with tagging so prod  can extend from base image

FROM python:3.6

ENV PYTHONUNBUFFERED 1
ENV WORKDDIR /app
WORKDIR ${WORKDDIR}
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install uwsgi
COPY . .
