version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["/app/entry.sh"]
    ports:
      - "80:8000"

    env_file:
      - ./env.secret
   
volumes:
    pgdata: