version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod

    command: uwsgi --http 0.0.0.0:8000 --module socialplatform.wsgi:application --processes 1 --threads 4
    ports:
      - "80:8000"


    env_file:
      - ./env.secret
   
volumes:
    pgdata: